# Generated by Django 5.1.3 on 2024-12-07 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_id_member_memberid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_joined', models.DateField(max_length=100)),
            ],
        ),
    ]
