# Generated by Django 5.1.3 on 2025-01-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_tournamentswonserializer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentsWonSerializer',
            new_name='Tournaments',
        ),
    ]
