# Generated by Django 5.1.3 on 2025-01-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_tournamentswonserializer_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('titles_won', models.DateField(null=True)),
                ('most_recent_win', models.CharField(max_length=100, null=True)),
                ('last_qualified', models.DateField(null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_won', to='members.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
