# Generated by Django 5.1.3 on 2025-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_tournament_delete_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='last_qualified',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
