# Generated by Django 5.1.3 on 2025-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_tournament_last_qualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='titles_won',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
