# Generated by Django 5.1.3 on 2025-01-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_tournament_titles_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='last_qualified',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='most_recent_win',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='titles_won',
        ),
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_teams',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TournamentsWon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_wins', models.DateField(null=True)),
                ('most_recent_win', models.CharField(max_length=100, null=True)),
                ('last_qualified', models.CharField(max_length=50, null=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='members.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ournaments_won', to='members.tournamentswon'),
        ),
    ]
