# Generated by Django 5.1.3 on 2025-01-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_tournament_last_qualified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentsWon',
            new_name='Tournaments_Won',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tournament',
            new_name='tournaments_won',
        ),
    ]
