# Generated by Django 5.1.3 on 2025-01-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_tournamentswon_tournaments_won_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments_Won',
            new_name='Tournaments_Win',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournaments_won',
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments_win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_win', to='members.tournaments_win'),
        ),
    ]
