# Generated by Django 5.1.3 on 2025-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_tournaments_won_tournaments_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments_win',
            name='number_of_wins',
            field=models.IntegerField(null=True),
        ),
    ]
