# Generated by Django 5.1.3 on 2025-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_tournaments_win_number_of_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournaments_win',
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments_win',
            field=models.ManyToManyField(null=True, related_name='teams', to='members.tournaments_win'),
        ),
    ]
