# Generated by Django 5.1.3 on 2025-01-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_team_tournaments_win_team_tournaments_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments_win',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_won', to='members.team'),
        ),
    ]
