# Generated by Django 5.1.3 on 2025-01-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_tournaments_win_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments_win',
            name='team',
        ),
        migrations.AlterField(
            model_name='tournaments_win',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_wins', to='members.tournament'),
        ),
    ]
