# Generated by Django 5.1.3 on 2025-01-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_tournaments_win_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournaments_win',
        ),
        migrations.CreateModel(
            name='Tournament_Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_wins', models.IntegerField(null=True)),
                ('most_recent_win', models.CharField(max_length=100, null=True)),
                ('last_qualified', models.CharField(max_length=50, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='members.team')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='members.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament_win',
            field=models.ManyToManyField(null=True, related_name='teams', to='members.tournament_win'),
        ),
        migrations.DeleteModel(
            name='Tournaments_Win',
        ),
    ]
