# Generated by Django 5.1.3 on 2025-01-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_remove_team_tournaments_win_tournament_win_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_win',
            name='team',
        ),
    ]
