# Generated by Django 5.1.3 on 2025-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_tournament_win_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament_win',
            field=models.ManyToManyField(null=True, related_name='team', to='members.tournament_win'),
        ),
    ]
