# Generated by Django 5.1.3 on 2025-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_team_tournament_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament_win',
            field=models.ManyToManyField(null=True, related_name='teams', to='members.tournament_win'),
        ),
    ]
