# Generated by Django 5.1.3 on 2025-01-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_team_tournament_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_win',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='members.team'),
        ),
    ]
