# Generated by Django 5.1.3 on 2025-01-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_tournament_win_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament_win',
        ),
    ]
